pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-downstream
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: Trigger
  desc: Trigger downstream repository builds
  type: clone
  image: plugins/drone-downstream
  labels:
    - trigger
    - drone
